sudo: required
services:
  - docker

before_install:
  - docker build -t gksanthosh/docker-react-new -f Dockerfile.dev .

script:
  - docker run -e CI=true gksanthosh/docker-react-new npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-new"
  env: "DockerReactNew-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-480828724423"
  bucket_path: "docker-react-new"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"